webtalk_init -webtalk_dir C:\\GIT\\Ultra96V2_DisplayPort\\display_port\\display_port.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-02-06 22:25:01" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176032993_1777485347_210642998_121" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "k8g386e38ttp21sba8l3sflqbu" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.074 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1580978034062" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key isZynqMP -value "true" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key Processors -value "7" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key Arch -value "zynquplus" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key Device -value "xczu3eg" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1580978034062"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1581027901744"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1581027901744"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1581027901744"
webtalk_add_data -client sdk -key DebugCount -value "25" -context "sdk\\\\bsp/1581027901744"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1581027901744"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1581027901744"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1581027901744"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1581027901744"
webtalk_transmit -clientid 206587038 -regid "176032993_1777485347_210642998_121" -xml C:\\GIT\\Ultra96V2_DisplayPort\\display_port\\display_port.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\GIT\\Ultra96V2_DisplayPort\\display_port\\display_port.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\GIT\\Ultra96V2_DisplayPort\\display_port\\display_port.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
