
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_height_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_width_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_bckgndId_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_ovrlayId_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_maskId_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_motionSpeed_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_colorFormat_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_crossHairX_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_crossHairY_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_ZplateHorContStart_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_ZplateHorContDelta_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_ZplateVerContStart_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_ZplateVerContDelta_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_boxSize_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_boxColorR_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_boxColorG_reg[*]]
set_false_path -from [get_cells v_tpg_CTRL_s_axi_U/int_boxColorB_reg[*]]

